CA-13 USUARIO (MVP): Ingresar a la aplicación
COLMASH/CrossFitApp-FrontEnd pull request #1
Opened 2021-06-14 03:50 UTC by COLMASH

Se crea la primera versión de la pagina de inicio que verá el usuario al ingresar a la aplicación. Incluye pagina de log-in común para todos los usuarios (cliente, coach y administrador).

2021-06-15 15:02 UTC, simonhoyos requested changes

2021-06-15 15:02 UTC, simonhoyos commented on src/App.js
> +  // Redirect,
No es bueno dejar código comentado. Esto se considera código muerto y hace que la complejidad del código se incremente. Es mejor borrarlo

2021-06-15 15:02 UTC, simonhoyos commented on src/components/FormInit.js
> +      </div>
Los botones deben ir dentro del formulario y solo debería haber un solo submit por formulario

2021-06-15 15:02 UTC, simonhoyos commented on src/components/MainUser/UserBar.jsx
> +      </button>
Semánticamente los botones son para cuando el usuario va a tener que realizar algun tipo de interacción con la página. En casos en los que se va a hacer navegación (vamos a cambiar de página) hay que usar links `a` o en este caso `Link` para que funcione con React Router Dom

2021-06-15 15:02 UTC, simonhoyos commented on src/components/MainUser/UserInfo.jsx
> +              <div className="col-sm-9 text-secondary">62</div>
Todo estos datos del usuario que van a variar y a ser dinámicos deberían estar mockeados por fuera del componente.

2021-06-15 15:02 UTC, simonhoyos commented on src/components/MainUser/UserNews.jsx
> +        </div>
Lo mismo que el comentario anterior. Esto debería estar mockeado por fuera componente

2021-06-15 15:02 UTC, simonhoyos commented on src/components/MainUser/UserProfile.jsx
> +              </div>
Lo mismo con la data mockeada

2021-06-15 15:48 UTC, NataliaBedoya reviewed
Se hacen los cambios sugeridos por Simón

2021-06-15 16:47 UTC, welfar approved these changes
revisión y corrección

2021-06-15 18:58 UTC, COLMASH commented on src/components/FormInit.js
> +      </div>
Atendido

2021-06-15 19:20 UTC, COLMASH commented on src/components/MainUser/UserNews.jsx
> +        </div>
Simón entendemos que tendriamos que mockear los links de las imágenes, nos confirmas si es así por favor?

2021-06-15 19:28 UTC, simonhoyos commented on src/components/MainUser/UserNews.jsx
> +        </div>
Sí, mockeen los links.

2021-06-15 23:33 UTC, simonhoyos approved these changes

2021-06-16 01:25 UTC, NataliaBedoya approved these changes

2021-06-16 01:32 UTC, merged