crea el registro de nuevo usuarios conectando FE y BE
COLMASH/CrossFitApp-FrontEnd pull request #12
Opened 2021-07-07 09:10 UTC by COLMASH

crea el registro de nuevos usuarios conectando FE y BE

2021-07-07 11:18 UTC, NataliaBedoya approved these changes

2021-07-07 12:18 UTC, simonhoyos requested changes

2021-07-07 12:18 UTC, simonhoyos commented on src/components/General/RegistrationModal.jsx
> +          getUserInfo(dataUserSignIn.token).then((resGetUserInfo) => {
Alguna razón para hacer estas 3 peticiones? No es necesario registrarse, inmediatamente hacer login, e inmediatamente obtener la información del usuario. En el BE se puede definir cualquier propiedad en el response, no se limiten al ejemplo de la clase. Por ejemplo en el register puedo responder con el token (ya no necesita hacer login), en el register puedo adicionalmente responder con la información del usuario que se acaba de registrar o de loggear y así no necesito hacer la petición adicional de getUserInfo

2021-07-07 12:18 UTC, simonhoyos commented on src/store/user/services.js
> +    console.log(error.message);
Sería bueno empezar a manejar los errores. El usuario final no ve la consola para ver que está pasando, siempre es bueno mostrarle al usuario lo que está pasando en la misma aplicación

2021-07-07 13:46 UTC, welfar approved these changes

2021-07-07 18:37 UTC, COLMASH commented on src/store/user/services.js
> +    console.log(error.message);
Si señor, hoy conversamos con el equipo y decidimos tenerlo en cuenta para las siguientes historias de usuario.

2021-07-08 12:46 UTC, simonhoyos approved these changes

2021-07-08 18:20 UTC, merged