Se agrega el perfil del coach
COLMASH/CrossFitApp-FrontEnd pull request #4
Opened 2021-06-17 21:57 UTC by welfar

2021-06-17 22:03 UTC, COLMASH approved these changes

2021-06-18 00:58 UTC, NataliaBedoya approved these changes

2021-06-18 11:48 UTC, simonhoyos requested changes
Muy bueno el código, lo único sería borra el archivo y reestablecer la identación de todos los archivos. Felicitaciones!!

2021-06-18 11:48 UTC, simonhoyos commented on src/styles/WODUser.css
> +  display: flex;
Este archivo se puede borrar. Solo tiene comentarios, es mejor no dejar código comentado

2021-06-18 11:48 UTC, simonhoyos commented on src/App.js
> +	state = {
Ojo con la indentación. Te recomiendo configurar tu editor de texto para que funcione igual que el de tus compañeros de equipo. Configura la indentación a 2 espacios y no a 4.

Por esa razón aparecen todos los archivos como modificados.

2021-06-18 15:26 UTC, simonhoyos approved these changes

2021-06-18 18:02 UTC, merged