Se hace la conexión FE-BE en el perfil del usuario
COLMASH/CrossFitApp-FrontEnd pull request #8
Opened 2021-06-30 21:42 UTC by NataliaBedoya

Se instala la librería jwt-decode.

2021-06-30 21:46 UTC, COLMASH approved these changes

2021-06-30 21:56 UTC, welfar approved these changes

2021-07-01 14:52 UTC, simonhoyos requested changes

2021-07-01 14:52 UTC, simonhoyos commented on src/components/General/FormInit.jsx
> +        console.log(tokenDecoded);
Borrar console.logs

2021-07-01 14:52 UTC, simonhoyos commented on src/components/General/FormInit.jsx
> +        const tokenDecoded = jwtDecode(dataUserSignIn.token);
Nunca decifren el token en el FE

2021-07-01 14:52 UTC, simonhoyos commented on src/components/General/FormInit.jsx
> +        getUserInfo(tokenDecoded.userId).then((resGetUserInfo) => {
En vez de pedir la información del usuario usando el userId lo pueden hacer enviando directamente el token al backend, que el backend lo decifre y obtenga la información del usuario loggeado

2021-07-01 14:52 UTC, simonhoyos commented on src/components/General/FormInit.jsx
> +          console.log(dataGetUserInfo);
Ojo con los console.logs

2021-07-03 04:41 UTC, NataliaBedoya commented on src/components/General/FormInit.jsx
> +        console.log(tokenDecoded);
R!

2021-07-03 11:55 UTC, welfar approved these changes

2021-07-03 21:45 UTC, simonhoyos approved these changes

2021-07-04 01:42 UTC, COLMASH approved these changes

2021-07-04 01:42 UTC, merged